In [25]:
# Arrays
# An array is a special variable, which can hold more than one value at a time.

cars = ["Ford", "Volvo", "BMW"]
print(cars)
print(cars[0])
# change 0th index value in array
cars[0]="Audi"
print(cars)

['Ford', 'Volvo', 'BMW']
Ford
['Audi', 'Volvo', 'BMW']


In [26]:
# length
print(len(cars))

3


In [27]:
# for in loop
for i in cars:
    print(i)

Audi
Volvo
BMW


In [28]:
# You can use the append() method to add an element to an array.

cars.append("Honda")
print(cars)

['Audi', 'Volvo', 'BMW', 'Honda']


In [29]:
# You can use the pop() method to remove an element from the array.

cars.pop(1)
print(cars)

['Audi', 'BMW', 'Honda']


In [30]:
# You can also use the remove() method to remove an element from the array.

cars.remove("Audi")
print(cars)

['BMW', 'Honda']


In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [33]:
np.arange(1, 10, 2) # (start ,end ,step)

array([1, 3, 5, 7, 9])

In [34]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# Create a NumPy array from 1 to 10.
import numpy as np

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
# Create a 3×3 matrix filled with 5.
arr = np.full((3,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [37]:
arr = np.array([10, 20, 30, 40])

print(arr[0])   # first element
print(arr[2])   # third element

10
30


In [38]:
print(arr[-1])

40


In [39]:
# Slicing
print(arr[1:4])

[20 30 40]


In [40]:
# 2d indexing
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])

2


In [41]:
# 2 d slicinf
print(arr[:, 1])

[2 5]


In [9]:
# Method	Description
# append()	Adds an element at the end of the list
# clear()	Removes all the elements from the list
# copy()	Returns a copy of the list
# count()	Returns the number of elements with the specified value
# extend()	Add the elements of a list (or any iterable), to the end of the current list
# index()	Returns the index of the first element with the specified value
# insert()	Adds an element at the specified position
# pop()	    Removes the element at the specified position
# remove()	Removes the first item with the specified value
# reverse()	Reverses the order of the list
# sort()	Sorts the list

In [10]:
import numpy as np
# Creating a 1D array
arr = np.array([10, 20, 30, 40])

In [11]:
import numpy as np

# Creating a 2D array (3 rows, 2 columns)
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix.shape)  # Output: (3, 2)

(3, 2)


In [12]:
# 2. Indexing and Slicing (Data Access)

# Indexing: array[row, column]

# Slicing: array[start:stop:step]

data = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90]])

# Access the number 50
print(data[1, 1]) 

# Slice the first two rows and last two columns
# Result: [[20, 30], [50, 60]]
print(data[0:2, 1:3])

50
[[20 30]
 [50 60]]


In [13]:
# Vectorization (Speed)

# Vectorization is the process of performing an operation 
#on an entire array at once rather than looping through 
#individual elements.
prices = np.array([100, 200, 300])

# Instead of: for p in prices: p * 1.1 (Slow)
discounted_prices = prices * 0.9 # Vectorized (Fast)

In [43]:
# Vectorization means performing operations on whole arrays WITHOUT loops.
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

[5 7 9]


In [44]:
arr = np.array([1,2,3,4,5,6])

print(arr[arr % 2 == 0])

[2 4 6]


In [15]:
# Broadcasting (Shape Flexibility)
# Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.
# Broadcasting means NumPy automatically adjusts array sizes during operations.

grades = np.array([[80, 85], [90, 70]]) # Shape (2, 2)
bonus = np.array([5, 10])               # Shape (2,)

# 'bonus' is broadcasted across both rows
# It becomes [[5, 10], [5, 10]] internally
final_grades = grades + bonus 
# Result: [[85, 95], [95, 80]]
print(final_grades)

[[85 95]
 [95 80]]


In [42]:
a = np.array([[1],[2],[3]])

b = np.array([10,20,30])

print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
